[package]
name = "sandboxed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build_dependencies]
bindgen = { path = "../bindgen" }

[dependencies]
mpk = { path = "../mpk" }
